In [2]:
# Import our dependencies
import pandas as pd

In [ ]:
#  Import and read the input csv
at_df = pd.read_csv('../Raw_Data/Cleaning_Completed/alcohol_tobacco_normalized.csv')
at_df

In [2]:
# Open the master list of countries
countries_df = pd.read_csv('../Clean_Data/country_profile_urls.csv')
countries_df = countries_df.drop(['profile_url'], 1)

C:\Temp\ipykernel_9292\822363187.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  countries_df = countries_df.drop(['profile_url'], 1)

In [3]:
country_list = countries_df['country'].tolist()
country_list

['Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Botswana',
 'Brazil',
 'British Virgin Islands',
 'Brunei Darussalam',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cabo Verde',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Congo',
 'Costa Rica',
 "Côte d'Ivoire",
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czechia',
 'Democratic Republic of the Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Fiji',
 'Finland',
 'France',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Grenada',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hong Kong (China)',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Ireland',
 'Isle of Man',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jersey',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Kuwait',
 'Kyrgyz Republic',
 "Lao People's Democratic Republic",
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Micronesia',
 'Moldova',
 'Monaco',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Macedonia',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Qatar',
 'Romania',
 'Russian Federation',
 'Rwanda',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'San Marino',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'South Africa',
 'South Korea',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syrian Arab Republic',
 'Taiwan (China)',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Togo',
 'Trinidad and Tobago',
 'Tunisia',
 'Türkiye',
 'Turkmenistan',
 'Uganda',
 'Ukraine',
 'United Kingdom',
 'United States of America',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela',
 'Vietnam',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [4]:
# Create a list of life Expectancy countries
at_countries = at_df['Country Name'].tolist()
at_countries

['Afghanistan',
 'Afghanistan',
 'Albania',
 'Albania',
 'Algeria',
 'Algeria',
 'Angola',
 'Angola',
 'Antigua and Barbuda',
 'Antigua and Barbuda',
 'Argentina',
 'Argentina',
 'Armenia',
 'Armenia',
 'Aruba',
 'Aruba',
 'Australia',
 'Australia',
 'Austria',
 'Austria',
 'Azerbaijan',
 'Azerbaijan',
 'Bahamas',
 'Bahamas',
 'Bahrain',
 'Bahrain',
 'Bangladesh',
 'Bangladesh',
 'Barbados',
 'Barbados',
 'Belarus',
 'Belarus',
 'Belgium',
 'Belgium',
 'Belize',
 'Belize',
 'Benin',
 'Benin',
 'Bhutan',
 'Bhutan',
 'Bolivia',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Bosnia and Herzegovina',
 'Botswana',
 'Botswana',
 'Brazil',
 'Brazil',
 'Brunei Darussalam',
 'Brunei Darussalam',
 'Bulgaria',
 'Bulgaria',
 'Burkina Faso',
 'Burkina Faso',
 'Burundi',
 'Burundi',
 'Cabo Verde',
 'Cabo Verde',
 'Cambodia',
 'Cambodia',
 'Cameroon',
 'Cameroon',
 'Canada',
 'Canada',
 'Central African Republic',
 'Central African Republic',
 'Chad',
 'Chad',
 'Channel Islands',
 'Channel Islands',
 'Chile',
 'Chile',
 'China',
 'China',
 'Colombia',
 'Colombia',
 'Comoros',
 'Comoros',
 'Democratic Republic of the Congo',
 'Democratic Republic of the Congo',
 'Congo',
 'Congo',
 'Costa Rica',
 'Costa Rica',
 "Côte d'Ivoire",
 "Côte d'Ivoire",
 'Croatia',
 'Croatia',
 'Cuba',
 'Cuba',
 'Cyprus',
 'Cyprus',
 'Czechia',
 'Czechia',
 'Denmark',
 'Denmark',
 'Djibouti',
 'Djibouti',
 'Dominican Republic',
 'Dominican Republic',
 'Ecuador',
 'Ecuador',
 'Egypt',
 'Egypt',
 'El Salvador',
 'El Salvador',
 'Equatorial Guinea',
 'Equatorial Guinea',
 'Eritrea',
 'Eritrea',
 'Estonia',
 'Estonia',
 'Eswatini',
 'Eswatini',
 'Ethiopia',
 'Ethiopia',
 'Fiji',
 'Fiji',
 'Finland',
 'Finland',
 'France',
 'France',
 'French Polynesia',
 'French Polynesia',
 'Gabon',
 'Gabon',
 'Gambia',
 'Gambia',
 'Georgia',
 'Georgia',
 'Germany',
 'Germany',
 'Ghana',
 'Ghana',
 'Greece',
 'Greece',
 'Grenada',
 'Grenada',
 'Guam',
 'Guam',
 'Guatemala',
 'Guatemala',
 'Guinea',
 'Guinea',
 'Guinea-Bissau',
 'Guinea-Bissau',
 'Guyana',
 'Guyana',
 'Haiti',
 'Haiti',
 'Honduras',
 'Honduras',
 'Hungary',
 'Hungary',
 'Iceland',
 'Iceland',
 'India',
 'India',
 'Indonesia',
 'Indonesia',
 'Iran',
 'Iran',
 'Iraq',
 'Iraq',
 'Ireland',
 'Ireland',
 'Israel',
 'Israel',
 'Italy',
 'Italy',
 'Jamaica',
 'Jamaica',
 'Japan',
 'Japan',
 'Jordan',
 'Jordan',
 'Kazakhstan',
 'Kazakhstan',
 'Kenya',
 'Kenya',
 'Kiribati',
 'Kiribati',
 "Korea, Dem. People's Rep.",
 "Korea, Dem. People's Rep.",
 'South Korea',
 'South Korea',
 'Kuwait',
 'Kuwait',
 'Kyrgyz Republic',
 'Kyrgyz Republic',
 "Lao People's Democratic Republic",
 "Lao People's Democratic Republic",
 'Latvia',
 'Latvia',
 'Lebanon',
 'Lebanon',
 'Lesotho',
 'Lesotho',
 'Liberia',
 'Liberia',
 'Libya',
 'Libya',
 'Lithuania',
 'Lithuania',
 'Luxembourg',
 'Luxembourg',
 'Madagascar',
 'Madagascar',
 'Malawi',
 'Malawi',
 'Malaysia',
 'Malaysia',
 'Maldives',
 'Maldives',
 'Mali',
 'Mali',
 'Malta',
 'Malta',
 'Mauritania',
 'Mauritania',
 'Mauritius',
 'Mauritius',
 'Mexico',
 'Mexico',
 'Micronesia',
 'Micronesia',
 'Moldova',
 'Moldova',
 'Mongolia',
 'Mongolia',
 'Montenegro',
 'Montenegro',
 'Morocco',
 'Morocco',
 'Mozambique',
 'Mozambique',
 'Myanmar',
 'Myanmar',
 'Namibia',
 'Namibia',
 'Nepal',
 'Nepal',
 'Netherlands',
 'Netherlands',
 'New Caledonia',
 'New Caledonia',
 'New Zealand',
 'New Zealand',
 'Nicaragua',
 'Nicaragua',
 'Niger',
 'Niger',
 'Nigeria',
 'Nigeria',
 'North Macedonia',
 'North Macedonia',
 'Northern Mariana Islands',
 'Northern Mariana Islands',
 'Norway',
 'Norway',
 'Oman',
 'Oman',
 'Pakistan',
 'Pakistan',
 'Panama',
 'Panama',
 'Papua New Guinea',
 'Papua New Guinea',
 'Paraguay',
 'Paraguay',
 'Peru',
 'Peru',
 'Philippines',
 'Philippines',
 'Poland',
 'Poland',
 'Portugal',
 'Portugal',
 'Puerto Rico',
 'Puerto Rico',
 'Qatar',
 'Qatar',
 'Romania',
 'Romania',
 'Russian Federation',
 'Russian Federation',
 'Rwanda',
 'Rwanda',
 'Samoa',
 'Samoa',
 'Sao Tome and Principe',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Saudi Arabia',
 'Senegal',
 'Senegal',
 'Serbia',
 'Serbia',
 'Sierra Leone',
 'Sierra Leone',
 'Singapore',
 'Singapore',
 'Sint Maarten (Dutch part)',
 'Sint Maarten (Dutch part)',
 'Slovakia',
 'Slovakia',
 'Slovenia',
 'Slovenia',
 'Solomon Islands',
 'Solomon Islands',
 'Somalia',
 'Somalia',
 'South Africa',
 'South Africa',
 'Spain',
 'Spain',
 'Sri Lanka',
 'Sri Lanka',
 'St. Kitts and Nevis',
 'St. Kitts and Nevis',
 'Saint Lucia',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'Saint Vincent and the Grenadines',
 'Sudan',
 'Sudan',
 'Suriname',
 'Suriname',
 'Sweden',
 'Sweden',
 'Switzerland',
 'Switzerland',
 'Syrian Arab Republic',
 'Syrian Arab Republic',
 'Tajikistan',
 'Tajikistan',
 'Tanzania',
 'Tanzania',
 'Thailand',
 'Thailand',
 'Timor-Leste',
 'Timor-Leste',
 'Togo',
 'Togo',
 'Tonga',
 'Tonga',
 'Trinidad and Tobago',
 'Trinidad and Tobago',
 'Tunisia',
 'Tunisia',
 'Turkiye',
 'Turkiye',
 'Turkmenistan',
 'Turkmenistan',
 'Uganda',
 'Uganda',
 'Ukraine',
 'Ukraine',
 'United Arab Emirates',
 'United Arab Emirates',
 'United Kingdom',
 'United Kingdom',
 'United States of America',
 'United States of America',
 'Uruguay',
 'Uruguay',
 'Uzbekistan',
 'Uzbekistan',
 'Vanuatu',
 'Vanuatu',
 'Venezuela',
 'Venezuela',
 'Vietnam',
 'Vietnam',
 'Yemen',
 'Yemen',
 'Zambia',
 'Zambia',
 'Zimbabwe',
 'Zimbabwe']

In [5]:
# clean the LE data based on the SS country list
no_match = []

for country in at_countries:
    if country in country_list:
        continue
    else:
        no_match.append(country)

In [6]:
no_match

['Afghanistan',
 'Afghanistan',
 'Bosnia and Herzegovina',
 'Bosnia and Herzegovina',
 'Channel Islands',
 'Channel Islands',
 'Comoros',
 'Comoros',
 'Eritrea',
 'Eritrea',
 'French Polynesia',
 'French Polynesia',
 'Guam',
 'Guam',
 'Iraq',
 'Iraq',
 "Korea, Dem. People's Rep.",
 "Korea, Dem. People's Rep.",
 'Maldives',
 'Maldives',
 'Mongolia',
 'Mongolia',
 'Montenegro',
 'Montenegro',
 'New Caledonia',
 'New Caledonia',
 'Northern Mariana Islands',
 'Northern Mariana Islands',
 'Puerto Rico',
 'Puerto Rico',
 'Sint Maarten (Dutch part)',
 'Sint Maarten (Dutch part)',
 'Somalia',
 'Somalia',
 'St. Kitts and Nevis',
 'St. Kitts and Nevis',
 'Timor-Leste',
 'Timor-Leste',
 'Tonga',
 'Tonga',
 'Turkiye',
 'Turkiye',
 'United Arab Emirates',
 'United Arab Emirates']

In [7]:
at_clean_df = at_df.drop(at_df[at_df['Country Name'].isin(no_match)].index.tolist())
at_clean_df

,Country Name,Series Name,2000 [YR2000],2001 [YR2001],2002 [YR2002],2003 [YR2003],2004 [YR2004],2005 [YR2005],2006 [YR2006],2007 [YR2007],...,2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019]
2,Albania,Total alcohol consumption per capita (liters o...,6.57,6.79,7,7.22,7.43,7.65,7.66,7.67,...,7.69,7.5,7.31,7.12,6.93,6.74,6.88,7.03,7.17,..
3,Albania,Prevalence of current tobacco use (% of adults),35,34.26,33.52,32.78,32.04,31.3,30.64,29.98,...,28,27.42,26.84,26.26,25.68,25.1,24.4,23.7,23,23
4,Algeria,Total alcohol consumption per capita (liters o...,0.58,0.63,0.67,0.72,0.76,0.81,0.78,0.75,...,0.65,0.71,0.76,0.82,0.87,0.93,0.94,0.94,0.95,..
5,Algeria,Prevalence of current tobacco use (% of adults),22.2,22.12,22.04,21.96,21.88,21.8,21.74,21.68,...,21.5,21.42,21.34,21.26,21.18,21.1,21.07,21.03,21,21
6,Angola,Total alcohol consumption per capita (liters o...,2.76,3.19,3.61,4.04,4.46,4.89,5.54,6.2,...,8.16,8.12,8.08,8.04,8,7.96,7.62,7.28,6.94,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,Yemen,Prevalence of current tobacco use (% of adults),27.3,26.9,26.5,26.1,25.7,25.3,24.92,24.54,...,23.4,23.08,22.76,22.44,22.12,21.8,21.37,20.93,20.5,20.5
376,Zambia,Total alcohol consumption per capita (liters o...,4.05,4.02,3.99,3.96,3.93,3.9,4.21,4.51,...,5.43,5.72,6.01,6.31,6.6,6.89,6.77,6.66,6.54,..
377,Zambia,Prevalence of current tobacco use (% of adults),19.9,19.54,19.18,18.82,18.46,18.1,17.82,17.54,...,16.7,16.46,16.22,15.98,15.74,15.5,15.2,14.9,14.6,14.6
378,Zimbabwe,Total alcohol consumption per capita (liters o...,2.46,2.52,2.58,2.65,2.71,2.77,3,3.23,...,3.93,4.13,4.33,4.52,4.72,4.92,4.84,4.75,4.67,..
379,Zimbabwe,Prevalence of current tobacco use (% of adults),21,20.42,19.84,19.26,18.68,18.1,17.6,17.1,...,15.6,15.2,14.8,14.4,14,13.6,13.1,12.6,12.1,12.1

In [8]:
at_clean_df.to_csv('at_clean.csv', index=False)

In [3]:
at_clean_df = pd.read_csv('at_clean.csv')
at_clean_df

,Country Name,Series Name,2000,2001,2002,2003,2004,2005,2006,2007,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Albania,Total alcohol consumption per capita (liters o...,6.57,6.79,7,7.22,7.43,7.65,7.66,7.67,...,7.69,7.5,7.31,7.12,6.93,6.74,6.88,7.03,7.17,..
1,Albania,Prevalence of current tobacco use (% of adults),35,34.26,33.52,32.78,32.04,31.3,30.64,29.98,...,28,27.42,26.84,26.26,25.68,25.1,24.4,23.7,23,23
2,Algeria,Total alcohol consumption per capita (liters o...,0.58,0.63,0.67,0.72,0.76,0.81,0.78,0.75,...,0.65,0.71,0.76,0.82,0.87,0.93,0.94,0.94,0.95,..
3,Algeria,Prevalence of current tobacco use (% of adults),22.2,22.12,22.04,21.96,21.88,21.8,21.74,21.68,...,21.5,21.42,21.34,21.26,21.18,21.1,21.07,21.03,21,21
4,Angola,Total alcohol consumption per capita (liters o...,2.76,3.19,3.61,4.04,4.46,4.89,5.54,6.2,...,8.16,8.12,8.08,8.04,8,7.96,7.62,7.28,6.94,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,Yemen,Prevalence of current tobacco use (% of adults),27.3,26.9,26.5,26.1,25.7,25.3,24.92,24.54,...,23.4,23.08,22.76,22.44,22.12,21.8,21.37,20.93,20.5,20.5
332,Zambia,Total alcohol consumption per capita (liters o...,4.05,4.02,3.99,3.96,3.93,3.9,4.21,4.51,...,5.43,5.72,6.01,6.31,6.6,6.89,6.77,6.66,6.54,..
333,Zambia,Prevalence of current tobacco use (% of adults),19.9,19.54,19.18,18.82,18.46,18.1,17.82,17.54,...,16.7,16.46,16.22,15.98,15.74,15.5,15.2,14.9,14.6,14.6
334,Zimbabwe,Total alcohol consumption per capita (liters o...,2.46,2.52,2.58,2.65,2.71,2.77,3,3.23,...,3.93,4.13,4.33,4.52,4.72,4.92,4.84,4.75,4.67,..
335,Zimbabwe,Prevalence of current tobacco use (% of adults),21,20.42,19.84,19.26,18.68,18.1,17.6,17.1,...,15.6,15.2,14.8,14.4,14,13.6,13.1,12.6,12.1,12.1

In [4]:
at_transform_df = at_clean_df.set_index('Country Name', 'Series Name').T
at_transform_df

C:\Temp\ipykernel_5960\1967187430.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.set_index except for the argument 'keys' will be keyword-only.
  at_transform_df = at_clean_df.set_index('Country Name', 'Series Name').T

Country Name,Albania,Albania,Algeria,Algeria,Angola,Angola,Antigua and Barbuda,Antigua and Barbuda,Argentina,Argentina,...,Venezuela,Venezuela,Vietnam,Vietnam,Yemen,Yemen,Zambia,Zambia,Zimbabwe,Zimbabwe
Series Name,Total alcohol consumption per capita (liters o...,Prevalence of current tobacco use (% of adults),Total alcohol consumption per capita (liters o...,Prevalence of current tobacco use (% of adults),Total alcohol consumption per capita (liters o...,Prevalence of current tobacco use (% of adults),Total alcohol consumption per capita (liters o...,Prevalence of current tobacco use (% of adults),Total alcohol consumption per capita (liters o...,Prevalence of current tobacco use (% of adults),...,Total alcohol consumption per capita (liters o...,Prevalence of current tobacco use (% of adults),Total alcohol consumption per capita (liters o...,Prevalence of current tobacco use (% of adults),Total alcohol consumption per capita (liters o...,Prevalence of current tobacco use (% of adults),Total alcohol consumption per capita (liters o...,Prevalence of current tobacco use (% of adults),Total alcohol consumption per capita (liters o...,Prevalence of current tobacco use (% of adults)
2000,6.57,35,0.58,22.2,2.76,..,5.13,..,8.75,34,...,9.15,..,2.21,29.8,0.79,27.3,4.05,19.9,2.46,21
2001,6.79,34.26,0.63,22.12,3.19,#VALUE!,5.18,#VALUE!,8.73,33.5,...,9.2,#VALUE!,2.29,29.5,0.7,26.9,4.02,19.54,2.52,20.42
2002,7,33.52,0.67,22.04,3.61,#VALUE!,5.23,#VALUE!,8.71,33,...,9.26,#VALUE!,2.38,29.2,0.61,26.5,3.99,19.18,2.58,19.84
2003,7.22,32.78,0.72,21.96,4.04,#VALUE!,5.27,#VALUE!,8.7,32.5,...,9.31,#VALUE!,2.46,28.9,0.52,26.1,3.96,18.82,2.65,19.26
2004,7.43,32.04,0.76,21.88,4.46,#VALUE!,5.32,#VALUE!,8.68,32,...,9.37,#VALUE!,2.55,28.6,0.43,25.7,3.93,18.46,2.71,18.68
2005,7.65,31.3,0.81,21.8,4.89,..,5.37,..,8.66,31.5,...,9.42,..,2.63,28.3,0.34,25.3,3.9,18.1,2.77,18.1
2006,7.66,30.64,0.78,21.74,5.54,#VALUE!,5.42,#VALUE!,8.75,30.98,...,9.27,#VALUE!,3.08,28.04,0.31,24.92,4.21,17.82,3,17.6
2007,7.67,29.98,0.75,21.68,6.2,#VALUE!,5.46,#VALUE!,8.83,30.46,...,9.12,#VALUE!,3.54,27.78,0.28,24.54,4.51,17.54,3.23,17.1
2008,7.67,29.32,0.71,21.62,6.85,#VALUE!,5.51,#VALUE!,8.92,29.94,...,8.97,#VALUE!,3.99,27.52,0.24,24.16,4.82,17.26,3.47,16.6
2009,7.68,28.66,0.68,21.56,7.51,#VALUE!,5.55,#VALUE!,9,29.42,...,8.82,#VALUE!,4.45,27.26,0.21,23.78,5.12,16.98,3.7,16.1
2010,7.69,28,0.65,21.5,8.16,..,5.6,..,9.09,28.9,...,8.67,..,4.9,27,0.18,23.4,5.43,16.7,3.93,15.6
2011,7.5,27.42,0.71,21.42,8.12,#VALUE!,5.66,#VALUE!,9.18,28.44,...,8.3,#VALUE!,5.49,26.8,0.16,23.08,5.72,16.46,4.13,15.2
2012,7.31,26.84,0.76,21.34,8.08,#VALUE!,5.72,#VALUE!,9.27,27.98,...,7.93,#VALUE!,6.08,26.6,0.13,22.76,6.01,16.22,4.33,14.8
2013,7.12,26.26,0.82,21.26,8.04,#VALUE!,5.77,#VALUE!,9.37,27.52,...,7.56,#VALUE!,6.68,26.4,0.11,22.44,6.31,15.98,4.52,14.4
2014,6.93,25.68,0.87,21.18,8,#VALUE!,5.83,#VALUE!,9.46,27.06,...,7.19,#VALUE!,7.27,26.2,0.08,22.12,6.6,15.74,4.72,14
2015,6.74,25.1,0.93,21.1,7.96,..,5.89,..,9.55,26.6,...,6.82,..,7.86,26,0.06,21.8,6.89,15.5,4.92,13.6
2016,6.88,24.4,0.94,21.07,7.62,#VALUE!,6.05,#VALUE!,9.58,26.03,...,5.93,#VALUE!,8.13,25.67,0.05,21.37,6.77,15.2,4.84,13.1
2017,7.03,23.7,0.94,21.03,7.28,#VALUE!,6.22,#VALUE!,9.62,25.47,...,5.03,#VALUE!,8.39,25.33,0.05,20.93,6.66,14.9,4.75,12.6
2018,7.17,23,0.95,21,6.94,..,6.38,..,9.65,24.9,...,4.14,..,8.66,25,0.05,20.5,6.54,14.6,4.67,12.1
2019,..,23,..,21,..,..,..,..,..,24.9,...,..,..,..,25,..,20.5,..,14.6,..,12.1

In [5]:
at_transform_df.to_csv('at_clean_transform.csv', index=False)