In [1]:
# Import our dependencies
import pandas as pd

In [2]:
#  Import and read the input csv
yd_df = pd.read_csv("young_deaths_cleaned.csv")
yd_df

,Country Name,Series Name,2000 [YR2000],2001 [YR2001],2002 [YR2002],2003 [YR2003],2004 [YR2004],2005 [YR2005],2006 [YR2006],2007 [YR2007],...,2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020]
0,Afghanistan,"Survival to age 65, male (% of cohort)",48.209619,48.902877,49.596135,50.398152,51.200169,52.002187,52.804204,53.606221,...,56.955055,57.792263,58.423871,59.055479,59.687087,60.318695,60.950303,61.494258,62.038214,62.582169
1,Afghanistan,"Survival to age 65, female (% of cohort)",54.133867,54.853346,55.572824,56.429403,57.285982,58.142561,58.999140,59.855719,...,63.402781,64.289546,64.946512,65.603478,66.260444,66.917410,67.574376,68.161778,68.749180,69.336582
2,Albania,"Survival to age 65, male (% of cohort)",78.304781,79.202819,80.100857,80.293390,80.485923,80.678456,80.870989,81.063522,...,82.467872,82.818960,83.195726,83.572491,83.949257,84.326022,84.702788,84.894321,85.085853,85.277386
3,Albania,"Survival to age 65, female (% of cohort)",87.623860,88.032359,88.440858,88.605522,88.770186,88.934850,89.099514,89.264178,...,90.647210,90.992968,91.023453,91.053939,91.084424,91.114910,91.145395,91.222573,91.299750,91.376928
4,Algeria,"Survival to age 65, male (% of cohort)",72.944406,73.708181,74.471957,75.269949,76.067942,76.865934,77.663927,78.461919,...,80.047075,80.443364,80.732599,81.021834,81.311068,81.600303,81.889538,82.124413,82.359288,82.594164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,"Yemen, Rep.","Survival to age 65, female (% of cohort)",63.043049,63.804695,64.566341,65.381700,66.197059,67.012417,67.827776,68.643135,...,70.389662,70.826294,70.841474,70.856654,70.871835,70.887015,70.902195,71.006354,71.110513,71.214671
358,Zambia,"Survival to age 65, male (% of cohort)",23.724823,24.178367,24.631911,26.221801,27.811691,29.401581,30.991471,32.581361,...,44.533605,47.521666,48.760630,49.999594,51.238559,52.477523,53.716487,54.198783,54.681079,55.163375
359,Zambia,"Survival to age 65, female (% of cohort)",32.282970,32.719670,33.156370,34.940938,36.725506,38.510074,40.294642,42.079210,...,54.093203,57.096701,59.006574,60.916447,62.826320,64.736193,66.646066,67.145937,67.645807,68.145678
360,Zimbabwe,"Survival to age 65, male (% of cohort)",17.514188,16.590177,15.666166,16.239989,16.813812,17.387634,17.961457,18.535280,...,36.771647,41.330739,42.897722,44.464705,46.031689,47.598672,49.165655,49.621611,50.077566,50.533522
361,Zimbabwe,"Survival to age 65, female (% of cohort)",27.482299,25.852100,24.221902,24.598367,24.974833,25.351298,25.727764,26.104229,...,44.471005,49.062699,50.409265,51.755831,53.102397,54.448963,55.795529,56.318774,56.842019,57.365265

In [3]:
yd_df = yd_df.drop(['Series Name'], 1)
yd_df

C:\Users\dsmel\anaconda3\envs\mlenv\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  """Entry point for launching an IPython kernel.

,Country Name,2000 [YR2000],2001 [YR2001],2002 [YR2002],2003 [YR2003],2004 [YR2004],2005 [YR2005],2006 [YR2006],2007 [YR2007],2008 [YR2008],...,2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020]
0,Afghanistan,48.209619,48.902877,49.596135,50.398152,51.200169,52.002187,52.804204,53.606221,54.443429,...,56.955055,57.792263,58.423871,59.055479,59.687087,60.318695,60.950303,61.494258,62.038214,62.582169
1,Afghanistan,54.133867,54.853346,55.572824,56.429403,57.285982,58.142561,58.999140,59.855719,60.742484,...,63.402781,64.289546,64.946512,65.603478,66.260444,66.917410,67.574376,68.161778,68.749180,69.336582
2,Albania,78.304781,79.202819,80.100857,80.293390,80.485923,80.678456,80.870989,81.063522,81.414610,...,82.467872,82.818960,83.195726,83.572491,83.949257,84.326022,84.702788,84.894321,85.085853,85.277386
3,Albania,87.623860,88.032359,88.440858,88.605522,88.770186,88.934850,89.099514,89.264178,89.609936,...,90.647210,90.992968,91.023453,91.053939,91.084424,91.114910,91.145395,91.222573,91.299750,91.376928
4,Algeria,72.944406,73.708181,74.471957,75.269949,76.067942,76.865934,77.663927,78.461919,78.858208,...,80.047075,80.443364,80.732599,81.021834,81.311068,81.600303,81.889538,82.124413,82.359288,82.594164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,"Yemen, Rep.",63.043049,63.804695,64.566341,65.381700,66.197059,67.012417,67.827776,68.643135,69.079767,...,70.389662,70.826294,70.841474,70.856654,70.871835,70.887015,70.902195,71.006354,71.110513,71.214671
358,Zambia,23.724823,24.178367,24.631911,26.221801,27.811691,29.401581,30.991471,32.581361,35.569422,...,44.533605,47.521666,48.760630,49.999594,51.238559,52.477523,53.716487,54.198783,54.681079,55.163375
359,Zambia,32.282970,32.719670,33.156370,34.940938,36.725506,38.510074,40.294642,42.079210,45.082708,...,54.093203,57.096701,59.006574,60.916447,62.826320,64.736193,66.646066,67.145937,67.645807,68.145678
360,Zimbabwe,17.514188,16.590177,15.666166,16.239989,16.813812,17.387634,17.961457,18.535280,23.094372,...,36.771647,41.330739,42.897722,44.464705,46.031689,47.598672,49.165655,49.621611,50.077566,50.533522
361,Zimbabwe,27.482299,25.852100,24.221902,24.598367,24.974833,25.351298,25.727764,26.104229,30.695923,...,44.471005,49.062699,50.409265,51.755831,53.102397,54.448963,55.795529,56.318774,56.842019,57.365265

In [4]:
yd_transform_df = yd_df.set_index('Country Name', 'Series Name').T
yd_transform_df

C:\Users\dsmel\anaconda3\envs\mlenv\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.set_index except for the argument 'keys' will be keyword-only
  """Entry point for launching an IPython kernel.

Country Name,Afghanistan,Afghanistan,Albania,Albania,Algeria,Algeria,Angola,Angola,Antigua and Barbuda,Antigua and Barbuda,...,"Venezuela, RB","Venezuela, RB",Vietnam,Vietnam,"Yemen, Rep.","Yemen, Rep.",Zambia,Zambia,Zimbabwe,Zimbabwe
2000 [YR2000],48.209619,54.133867,78.304781,87.623860,72.944406,78.627408,34.537367,43.421922,74.296341,84.031397,...,68.875974,82.120969,69.244649,84.986971,56.224615,63.043049,23.724823,32.282970,17.514188,27.482299
2001 [YR2001],48.902877,54.853346,79.202819,88.032359,73.708181,79.216365,35.003473,44.109760,74.746877,84.374279,...,69.149740,82.562338,69.430343,85.175221,56.977316,63.804695,24.178367,32.719670,16.590177,25.852100
2002 [YR2002],49.596135,55.572824,80.100857,88.440858,74.471957,79.805321,35.469578,44.797597,75.197414,84.717160,...,69.423506,83.003706,69.616037,85.363471,57.730017,64.566341,24.631911,33.156370,15.666166,24.221902
2003 [YR2003],50.398152,56.429403,80.293390,88.605522,75.269949,80.413913,36.525852,46.164482,75.670497,84.979701,...,69.537594,83.119879,69.925042,85.481573,58.519651,65.381700,26.221801,34.940938,16.239989,24.598367
2004 [YR2004],51.200169,57.285982,80.485923,88.770186,76.067942,81.022505,37.582126,47.531367,76.143581,85.242241,...,69.651681,83.236052,70.234048,85.599675,59.309285,66.197059,27.811691,36.725506,16.813812,24.974833
2005 [YR2005],52.002187,58.142561,80.678456,88.934850,76.865934,81.631096,38.638400,48.898253,76.616664,85.504782,...,69.765769,83.352225,70.543053,85.717778,60.098919,67.012417,29.401581,38.510074,17.387634,25.351298
2006 [YR2006],52.804204,58.999140,80.870989,89.099514,77.663927,82.239688,39.694674,50.265138,77.089748,85.767322,...,69.879856,83.468398,70.852059,85.835880,60.888553,67.827776,30.991471,40.294642,17.961457,25.727764
2007 [YR2007],53.606221,59.855719,81.063522,89.264178,78.461919,82.848280,40.750948,51.632023,77.562831,86.029863,...,69.993944,83.584571,71.161064,85.953982,61.678187,68.643135,32.581361,42.079210,18.535280,26.104229
2008 [YR2008],54.443429,60.742484,81.414610,89.609936,78.858208,83.169500,42.063763,53.202172,77.818305,86.090138,...,70.047524,83.595617,71.235452,86.029617,62.087388,69.079767,35.569422,45.082708,23.094372,30.695923
2009 [YR2009],55.280638,61.629250,81.765697,89.955694,79.254497,83.490720,43.376577,54.772322,78.073778,86.150412,...,70.101103,83.606662,71.309839,86.105253,62.496589,69.516399,38.557483,48.086206,27.653464,35.287617
2010 [YR2010],56.117846,62.516015,82.116785,90.301452,79.650786,83.811939,44.689392,56.342471,78.329252,86.210687,...,70.154683,83.617708,71.384227,86.180888,62.905789,69.953030,41.545544,51.089705,32.212555,39.879311
2011 [YR2011],56.955055,63.402781,82.467872,90.647210,80.047075,84.133159,46.002206,57.912621,78.584725,86.270961,...,70.208262,83.628753,71.458614,86.256524,63.314990,70.389662,44.533605,54.093203,36.771647,44.471005
2012 [YR2012],57.792263,64.289546,82.818960,90.992968,80.443364,84.454379,47.315021,59.482770,78.840199,86.331236,...,70.261842,83.639799,71.533002,86.332159,63.724191,70.826294,47.521666,57.096701,41.330739,49.062699
2013 [YR2013],58.423871,64.946512,83.195726,91.023453,80.732599,84.729384,47.978956,60.319365,79.138064,86.346415,...,70.078753,83.438405,71.596384,86.401192,63.733015,70.841474,48.760630,59.006574,42.897722,50.409265
2014 [YR2014],59.055479,65.603478,83.572491,91.053939,81.021834,85.004389,48.642891,61.155960,79.435929,86.361594,...,69.895664,83.237012,71.659766,86.470226,63.741840,70.856654,49.999594,60.916447,44.464705,51.755831
2015 [YR2015],59.687087,66.260444,83.949257,91.084424,81.311068,85.279395,49.306825,61.992556,79.733793,86.376774,...,69.712574,83.035618,71.723148,86.539259,63.750664,70.871835,51.238559,62.826320,46.031689,53.102397
2016 [YR2016],60.318695,66.917410,84.326022,91.114910,81.600303,85.554400,49.970760,62.829151,80.031658,86.391953,...,69.529485,82.834225,71.786530,86.608293,63.759489,70.887015,52.477523,64.736193,47.598672,54.448963
2017 [YR2017],60.950303,67.574376,84.702788,91.145395,81.889538,85.829405,50.634695,63.665746,80.329523,86.407132,...,69.346396,82.632831,71.849912,86.677326,63.768313,70.902195,53.716487,66.646066,49.165655,55.795529
2018 [YR2018],61.494258,68.161778,84.894321,91.222573,82.124413,86.051009,51.136969,64.186799,80.520076,86.582873,...,69.404248,82.677487,72.027034,86.774129,63.844025,71.006354,54.198783,67.145937,49.621611,56.318774
2019 [YR2019],62.038214,68.749180,85.085853,91.299750,82.359288,86.272614,51.639242,64.707852,80.710629,86.758614,...,69.462100,82.722143,72.204157,86.870932,63.919737,71.110513,54.681079,67.645807,50.077566,56.842019
2020 [YR2020],62.582169,69.336582,85.277386,91.376928,82.594164,86.494218,52.141516,65.228905,80.901181,86.934356,...,69.519951,82.766799,72.381279,86.967736,63.995448,71.214671,55.163375,68.145678,50.533522,57.365265

In [5]:
yd_transform_df.to_csv('yd_clean-transform.csv')