In [1]:
# Import our dependencies
import pandas as pd

#  Import and read the charity_data.csv
systems_df = pd.read_csv("country_social_security_systems.csv")
systems_df

,country,system_type,profile_data_date
0,Albania,Universal (medical benefits) and social insura...,January 2018
1,Algeria,Social insurance system,January 2019
2,Andorra,Social insurance system,January 2018
3,Angola,"Universal (medical benefits), social insurance...",January 2019
4,Antigua and Barbuda,Social insurance system,July 2019
...,...,...,...
179,Venezuela,Universal (birth grant and medical benefits) a...,July 2019
180,Vietnam,Social insurance system,July 2018
181,Yemen,Universal (medical benefits) and employer-liab...,July 2018
182,Zambia,Universal (medical benefits) and employer-liab...,January 2019
183,Zimbabwe,Employer-liability system. Cash sickness and m...,January 2019

In [12]:
gdp_df = pd.read_csv('../Raw_Data/GDP_en_csv_v2_4701247.csv')
gdp_df = gdp_df.drop(['Country Code', 'Indicator Code'], 1)
gdp_df.dtypes

C:\Temp\ipykernel_6540\376940624.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  gdp_df = gdp_df.drop(['Country Code', 'Indicator Code'], 1)

Country Name       object
Indicator Name     object
1960              float64
1961              float64
1962              float64
                   ...
2018              float64
2019              float64
2020              float64
2021              float64
Unnamed: 66       float64
Length: 65, dtype: object

In [3]:
gdp_countries = gdp_df['Country Name'].tolist()
gdp_countries

['Aruba',
 'Africa Eastern and Southern',
 'Afghanistan',
 'Africa Western and Central',
 'Angola',
 'Albania',
 'Andorra',
 'Arab World',
 'United Arab Emirates',
 'Argentina',
 'Armenia',
 'American Samoa',
 'Antigua and Barbuda',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Burundi',
 'Belgium',
 'Benin',
 'Burkina Faso',
 'Bangladesh',
 'Bulgaria',
 'Bahrain',
 'Bahamas',
 'Bosnia and Herzegovina',
 'Belarus',
 'Belize',
 'Bermuda',
 'Bolivia',
 'Brazil',
 'Barbados',
 'Brunei Darussalam',
 'Bhutan',
 'Botswana',
 'Central African Republic',
 'Canada',
 'Central Europe and the Baltics',
 'Switzerland',
 'Channel Islands',
 'Chile',
 'China',
 "Côte d'Ivoire",
 'Cameroon',
 'Democratic Republic of the Congo',
 'Congo',
 'Colombia',
 'Comoros',
 'Cabo Verde',
 'Costa Rica',
 'Caribbean small states',
 'Cuba',
 'Curacao',
 'Cayman Islands',
 'Cyprus',
 'Czechia',
 'Germany',
 'Djibouti',
 'Dominica',
 'Denmark',
 'Dominican Republic',
 'Algeria',
 'East Asia & Pacific (excluding high income)',
 'Early-demographic dividend',
 'East Asia & Pacific',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia',
 'Ecuador',
 'Egypt',
 'Euro area',
 'Eritrea',
 'Spain',
 'Estonia',
 'Ethiopia',
 'European Union',
 'Fragile and conflict affected situations',
 'Finland',
 'Fiji',
 'France',
 'Faroe Islands',
 'Micronesia',
 'Gabon',
 'United Kingdom',
 'Georgia',
 'Ghana',
 'Gibraltar',
 'Guinea',
 'Gambia',
 'Guinea-Bissau',
 'Equatorial Guinea',
 'Greece',
 'Grenada',
 'Greenland',
 'Guatemala',
 'Guam',
 'Guyana',
 'High income',
 'Hong Kong (China)',
 'Honduras',
 'Heavily indebted poor countries (HIPC)',
 'Croatia',
 'Haiti',
 'Hungary',
 'IBRD only',
 'IDA & IBRD total',
 'IDA total',
 'IDA blend',
 'Indonesia',
 'IDA only',
 'Isle of Man',
 'India',
 'Not classified',
 'Ireland',
 'Iran',
 'Iraq',
 'Iceland',
 'Israel',
 'Italy',
 'Jamaica',
 'Jordan',
 'Japan',
 'Kazakhstan',
 'Kenya',
 'Kyrgyz Republic',
 'Cambodia',
 'Kiribati',
 'Saint Kitts and Nevis',
 'South Korea',
 'Kuwait',
 'Latin America & Caribbean (excluding high income)',
 "Lao People's Democratic Republic",
 'Lebanon',
 'Liberia',
 'Libya',
 'Saint Lucia',
 'Latin America & Caribbean',
 'Least developed countries: UN classification',
 'Low income',
 'Liechtenstein',
 'Sri Lanka',
 'Lower middle income',
 'Low & middle income',
 'Lesotho',
 'Late-demographic dividend',
 'Lithuania',
 'Luxembourg',
 'Latvia',
 'Macao SAR, China',
 'St. Martin (French part)',
 'Morocco',
 'Monaco',
 'Moldova',
 'Madagascar',
 'Maldives',
 'Middle East & North Africa',
 'Mexico',
 'Marshall Islands',
 'Middle income',
 'North Macedonia',
 'Mali',
 'Malta',
 'Myanmar',
 'Middle East & North Africa (excluding high income)',
 'Montenegro',
 'Mongolia',
 'Northern Mariana Islands',
 'Mozambique',
 'Mauritania',
 'Mauritius',
 'Malawi',
 'Malaysia',
 'North America',
 'Namibia',
 'New Caledonia',
 'Niger',
 'Nigeria',
 'Nicaragua',
 'Netherlands',
 'Norway',
 'Nepal',
 'Nauru',
 'New Zealand',
 'OECD members',
 'Oman',
 'Other small states',
 'Pakistan',
 'Panama',
 'Peru',
 'Philippines',
 'Palau',
 'Papua New Guinea',
 'Poland',
 'Pre-demographic dividend',
 'Puerto Rico',
 "Korea, Dem. People's Rep.",
 'Portugal',
 'Paraguay',
 'West Bank and Gaza',
 'Pacific island small states',
 'Post-demographic dividend',
 'French Polynesia',
 'Qatar',
 'Romania',
 'Russian Federation',
 'Rwanda',
 'South Asia',
 'Saudi Arabia',
 'Sudan',
 'Senegal',
 'Singapore',
 'Solomon Islands',
 'Sierra Leone',
 'El Salvador',
 'San Marino',
 'Somalia',
 'Serbia',
 'Sub-Saharan Africa (excluding high income)',
 'South Sudan',
 'Sub-Saharan Africa',
 'Small states',
 'Sao Tome and Principe',
 'Suriname',
 'Slovak Republic',
 'Slovenia',
 'Sweden',
 'Eswatini',
 'Sint Maarten (Dutch part)',
 'Seychelles',
 'Syrian Arab Republic',
 'Turks and Caicos Islands',
 'Chad',
 'East Asia & Pacific (IDA & IBRD countries)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Togo',
 'Thailand',
 'Tajikistan',
 'Turkmenistan',
 'Latin America & the Caribbean (IDA & IBRD countries)',
 'Timor-Leste',
 'Middle East & North Africa (IDA & IBRD countries)',
 'Tonga',
 'South Asia (IDA & IBRD)',
 'Sub-Saharan Africa (IDA & IBRD countries)',
 'Trinidad and Tobago',
 'Tunisia',
 'Türkiye',
 'Tuvalu',
 'Tanzania',
 'Uganda',
 'Ukraine',
 'Upper middle income',
 'Uruguay',
 'United States of America',
 'Uzbekistan',
 'Saint Vincent and the Grenadines',
 'Venezuela, RB',
 'British Virgin Islands',
 'Virgin Islands (U.S.)',
 'Vietnam',
 'Vanuatu',
 'World',
 'Samoa',
 'Kosovo',
 'Yemen',
 'South Africa',
 'Zambia',
 'Zimbabwe']

In [2]:
countries_df = pd.read_csv('../Clean_Data/country_profile_urls.csv')
countries_df = countries_df.drop(['profile_url'], 1)

C:\Temp\ipykernel_16048\2842728193.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  countries_df = countries_df.drop(['profile_url'], 1)

In [3]:
country_list = countries_df['country'].tolist()
country_list

['Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Botswana',
 'Brazil',
 'British Virgin Islands',
 'Brunei Darussalam',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cabo Verde',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Congo',
 'Costa Rica',
 "Côte d'Ivoire",
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czechia',
 'Democratic Republic of the Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Fiji',
 'Finland',
 'France',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Grenada',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hong Kong (China)',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Ireland',
 'Isle of Man',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jersey',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Kuwait',
 'Kyrgyz Republic',
 "Lao People's Democratic Republic",
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Micronesia',
 'Moldova',
 'Monaco',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Macedonia',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Qatar',
 'Romania',
 'Russian Federation',
 'Rwanda',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'San Marino',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'South Africa',
 'South Korea',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syrian Arab Republic',
 'Taiwan (China)',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Togo',
 'Trinidad and Tobago',
 'Tunisia',
 'Türkiye',
 'Turkmenistan',
 'Uganda',
 'Ukraine',
 'United Kingdom',
 'United States of America',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela',
 'Vietnam',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [6]:
# clean the GDP data based on the SS country list
no_match = []

for country in gdp_countries:
    if country in country_list:
        continue
    else:
        no_match.append(country)

In [7]:
no_match

['Africa Eastern and Southern',
 'Afghanistan',
 'Africa Western and Central',
 'Arab World',
 'United Arab Emirates',
 'American Samoa',
 'Bosnia and Herzegovina',
 'Central Europe and the Baltics',
 'Channel Islands',
 'Comoros',
 'Caribbean small states',
 'Curacao',
 'Cayman Islands',
 'East Asia & Pacific (excluding high income)',
 'Early-demographic dividend',
 'East Asia & Pacific',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia',
 'Euro area',
 'Eritrea',
 'European Union',
 'Fragile and conflict affected situations',
 'Faroe Islands',
 'Gibraltar',
 'Greenland',
 'Guam',
 'High income',
 'Heavily indebted poor countries (HIPC)',
 'IBRD only',
 'IDA & IBRD total',
 'IDA total',
 'IDA blend',
 'IDA only',
 'Not classified',
 'Iraq',
 'Latin America & Caribbean (excluding high income)',
 'Latin America & Caribbean',
 'Least developed countries: UN classification',
 'Low income',
 'Lower middle income',
 'Low & middle income',
 'Late-demographic dividend',
 'Macao SAR, China',
 'St. Martin (French part)',
 'Maldives',
 'Middle East & North Africa',
 'Middle income',
 'Middle East & North Africa (excluding high income)',
 'Montenegro',
 'Mongolia',
 'Northern Mariana Islands',
 'North America',
 'New Caledonia',
 'Nauru',
 'OECD members',
 'Other small states',
 'Pre-demographic dividend',
 'Puerto Rico',
 "Korea, Dem. People's Rep.",
 'West Bank and Gaza',
 'Pacific island small states',
 'Post-demographic dividend',
 'French Polynesia',
 'South Asia',
 'Somalia',
 'Sub-Saharan Africa (excluding high income)',
 'South Sudan',
 'Sub-Saharan Africa',
 'Small states',
 'Slovak Republic',
 'Sint Maarten (Dutch part)',
 'Turks and Caicos Islands',
 'East Asia & Pacific (IDA & IBRD countries)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Latin America & the Caribbean (IDA & IBRD countries)',
 'Timor-Leste',
 'Middle East & North Africa (IDA & IBRD countries)',
 'Tonga',
 'South Asia (IDA & IBRD)',
 'Sub-Saharan Africa (IDA & IBRD countries)',
 'Tuvalu',
 'Upper middle income',
 'Venezuela, RB',
 'Virgin Islands (U.S.)',
 'World',
 'Kosovo']

In [25]:
gdp_clean_df = gdp_df.drop(gdp_df[gdp_df['Country Name'].isin(no_match)].index.tolist())
gdp_clean_df

,Country Name,Indicator Name,1960,1961,1962,1963,1964,1965,1966,1967,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,Unnamed: 66
0,Aruba,GDP (current US$),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.727933e+09,2.791061e+09,2.963128e+09,2.983799e+09,3.092179e+09,3.202235e+09,3.310056e+09,2.496648e+09,NaN,NaN
4,Angola,GDP (current US$),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.334016e+11,1.372444e+11,8.721929e+10,4.984049e+10,6.897276e+10,7.779294e+10,6.930910e+10,5.361907e+10,7.254699e+10,NaN
5,Albania,GDP (current US$),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.277622e+10,1.322815e+10,1.138685e+10,1.186120e+10,1.301969e+10,1.515643e+10,1.540183e+10,1.513187e+10,1.826004e+10,NaN
6,Andorra,GDP (current US$),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.193513e+09,3.271686e+09,2.789881e+09,2.896610e+09,3.000162e+09,3.218420e+09,3.155149e+09,2.891001e+09,3.329911e+09,NaN
9,Argentina,GDP (current US$),NaN,NaN,2.445060e+10,1.827212e+10,2.560525e+10,2.834471e+10,2.863047e+10,2.425667e+10,...,5.520251e+11,5.263197e+11,5.947493e+11,5.575314e+11,6.436287e+11,5.248197e+11,4.528184e+11,3.895910e+11,4.914927e+11,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,Samoa,GDP (current US$),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.700596e+08,7.568060e+08,7.883073e+08,7.994939e+08,8.320256e+08,8.212869e+08,8.520071e+08,8.071475e+08,7.883900e+08,NaN
262,Yemen,GDP (current US$),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.041524e+10,4.322859e+10,4.244450e+10,3.131783e+10,2.684223e+10,2.160616e+10,2.188761e+10,1.884051e+10,2.106169e+10,NaN
263,South Africa,GDP (current US$),8.748597e+09,9.225996e+09,9.813996e+09,1.085420e+10,1.195600e+10,1.306899e+10,1.421139e+10,1.582139e+10,...,4.008860e+11,3.811989e+11,3.467098e+11,3.235855e+11,3.814488e+11,4.048421e+11,3.879346e+11,3.354421e+11,4.199464e+11,NaN
264,Zambia,GDP (current US$),7.130000e+08,6.962857e+08,6.931429e+08,7.187143e+08,8.394286e+08,1.082857e+09,1.264286e+09,1.368000e+09,...,2.803724e+10,2.714102e+10,2.125122e+10,2.095841e+10,2.587360e+10,2.631159e+10,2.330867e+10,1.811063e+10,2.120306e+10,NaN
265,Zimbabwe,GDP (current US$),1.052990e+09,1.096647e+09,1.117602e+09,1.159512e+09,1.217138e+09,1.311436e+09,1.281750e+09,1.397002e+09,...,1.909102e+10,1.949552e+10,1.996312e+10,2.054868e+10,1.758489e+10,1.811554e+10,1.928429e+10,1.805117e+10,2.621773e+10,NaN

In [33]:
gdp_clean_df = gdp_clean_df.drop(gdp_clean_df.columns[gdp_clean_df.columns.str.contains('^1')], axis=1)
gdp_clean_df = gdp_clean_df.drop(['Unnamed: 66'], 1)

C:\Temp\ipykernel_6540\4253563597.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  gdp_clean_df = gdp_clean_df.drop(['Unnamed: 66'], 1)

In [34]:
gdp_clean_df.to_csv('gdp_clean.csv', index=False)